### ISSUE TITLE
Purple box over text

### ISSUE THREAD

**Issue by PeanutButler** [orian34/matsuribayashi#9]
## Bug Information

**Describe the bug**: [The text of the game is covered by a purple box making it difficult to navigate]

**To reproduce**: [Launch the game]

**Expected behavior**: [The game should display the text]

## Install Information

**The game**: You should only report Higurashi Ch.8 related issues in this repository.

**The mod variant**: [Full]

**I installed the patch**: [Using the Installer]

**I bought the game at**: [GOG]

**Mod Install Date**: [Today but I first tried a week ago and had the same issue]

## System Information

**My operating system is**: [MacOS]

## Screenshots

**Attach screenshots here if applicable**

![Image 08-07-2023 à 07 57](https://github.com/orian34/matsuribayashi/assets/61251170/7b1270d0-fa2d-4fa9-b863-7d29c4d46c47)

If you need help locating logs or writing a bug report, see this page: https://07th-mod.com/wiki/Higurashi/support/

**Comment by orian34** [comment]
> 5 - Par défaut, le fichier sharedassets0.assets correspond à la version Steam de Windows.
Si jamais votre système d’exploitation et/ou version du jeu diffère de cette dernière, vous pouvez
renommer le fichier qui correspond à votre situation en « sharedassets0 ».
Une fois que vous vous êtes assuré du bon fonctionnement du patch, vous pouvez éventuellement
supprimer les fichiers sharedassets0.assets qui ne correspondent pas à votre version.

Make sure to check those files out and that the corresponding one is renamed to sharedassets0.

**Comment by drojf** [comment]
@PeanutButler 
uhh...I'm checking something right now, please don't try anything yet, you might have a configuration you can't fix with the french sharedassets files

**Comment by drojf** [comment]
@PeanutButler I think Orian is right, but you'll need to re-download the sharedassets files, since I think the installer would have deleted them.

Please download and extract this file: https://github.com/orian34/matsuribayashi/releases/download/v1.6.0/Matsuribayashi.Patch.FR.7z

Then follow the manual install instructions orian posted. You want to choose the `LinuxMac-GOG-2017.2.5-sharedassets0.languagespecificassets` file and rename it to `sharedassets0.assets`

----

Also, if you have the install logs (in your browser downloads as a `07th-mod-logs.zip` file), that would be very useful to us

**Comment by PeanutButler** [comment]
> @PeanutButler I think Orian is right, but you'll need to re-download the sharedassets files, since I think the installer would have deleted them.
> 
> Please download and extract this file: https://github.com/orian34/matsuribayashi/releases/download/v1.6.0/Matsuribayashi.Patch.FR.7z
> 
> Then follow the manual install instructions orian posted. You want to choose the `LinuxMac-GOG-2017.2.5-sharedassets0.languagespecificassets` file and rename it to `sharedassets0.assets`
> 
> Also, if you have the install logs (in your browser downloads as a `07th-mod-logs.zip` file), that would be very useful to us

thank your for your answer, I tried and it didn't work, I don't know if I did something wrong. I have the install logs but im not sure how to share it here (sorry im not used to post here or deal with games installation issues at all !)

**Comment by orian34** [comment]
You can attach files to your posts by dragging them directly.

**Comment by drojf** [comment]
I had a quick look at the installer and it should have already installed the GOG version by default....so perhaps the issue is something else (perhaps need a new sharedassetsfile just for mac + gog? but I would have thought we would have encountered this issue on the normal English install by now).

However, I still need to get the install logs to confirm this.

There is a github page about "Attaching files": https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

> To attach a file to an issue or pull request conversation, drag and drop it into the comment box. Alternatively, you can click the bar at the bottom of the comment box to browse, select, and add a file from your computer.

**Comment by PeanutButler** [comment]
[07th-mod-logs (9).zip](https://github.com/orian34/matsuribayashi/files/11990563/07th-mod-logs.9.zip)


> I had a quick look at the installer and it should have already installed the GOG version by default....so perhaps the issue is something else (perhaps need a new sharedassetsfile just for mac + gog? but I would have thought we would have encountered this issue on the normal English install by now).
> 
> However, I still need to get the install logs to confirm this.
> 
> There is a github page about "Attaching files": https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
> 
> > To attach a file to an issue or pull request conversation, drag and drop it into the comment box. Alternatively, you can click the bar at the bottom of the comment box to browse, select, and add a file from your computer.

here
[07th-mod-logs (9).zip](https://github.com/orian34/matsuribayashi/files/11990631/07th-mod-logs.9.zip)

**Comment by drojf** [comment]
Hi, can you try the following `sharedassets0.assets` for me? I just want to see which ones work, even if they're not in french.

----

1. Try the `LinuxMac-MG-Steam-2017.2.5-sharedassets0.languagespecificassets` (in the ['french patch' files](https://github.com/orian34/matsuribayashi/releases/download/v1.6.0/Matsuribayashi.Patch.FR.7z) you downloaded before, we asked you to try the GOG Version - now I want you to try the other non-GOG version)

----

2. Try the stock Mac GOG ENGLISH sharedassets. This should work, as it is the ones that come with the unmodded game: 
[download from here: stock sharedassets0.zip](https://github.com/orian34/matsuribayashi/files/11994103/stock.sharedassets0.zip) . 
   - If this version works and you choose to use it, note that the option sliders in the menu will be labelled incorrectly

----
3. Try the modded ENGLISH sharedassets: https://07th-mod.com/rikachama/ui/Matsuribayashi-UI_2017.2.5_unix.7z

----

Note that 2 and 3 make the UI in English (like buttons etc), but the game text willl still be in French, so you can still play the game that way.

**Comment by PeanutButler** [comment]
Hello ! Thank you for your answer, I tried all of that but it still didn't work. I don't know if I miss a step here. Also I tried to begin the game anyway and the text was all in Japanese even if the first pages indicated it was the French patch. I wonder if I should just try to play with the english patch then ?

**Comment by drojf** [comment]
Sounds like a good idea (even if it just to make sure the normal English mod works)

**Please make sure to tick the "Force Install From Scratch" to make sure all the French files are overwritten**:

![image](https://github.com/orian34/matsuribayashi/assets/1249449/a284ad86-4394-42a4-b523-9e70bfcd4cd5)

Then the download preview should show all the files being re-installed except "restore-bgm-se"

**Comment by PeanutButler** [comment]
Thank you, it works with the english mod !

**Comment by drojf** [comment]
Ah, cool, you can just continue to play the english version. The notes below are just for me and orian

----

I think to resolve this issue, I just need to re-build the French unix sharedassets for this chapter.

After some investigation, there should only be two variants, the "windows" version, and the "unix" version (there are currently 3 variants in the archive, but I don't think they are necessary anymore).

@orian34, I forgot, where do you keep the original files (like translated images of the UI) for the french sharedassets?

**Comment by drojf** [comment]
I think I know what causes this now, see https://github.com/07th-mod/python-patcher/issues/215

Also, note that this also happens on the Linux Ch.8 GOG release. Since I can reproduce it, it should be easier to fix.

**Comment by drojf** [comment]
This should be fixed now, due to updating the installer and updating the sharedassets for french ch.8.

- Properly handle unity version upgrades when selecting translation sharedassets: https://github.com/07th-mod/python-patcher/issues/215
- Update french sharedassets - remove unnecessary old GOG sharedassets: https://github.com/orian34/matsuribayashi/releases/tag/v1.6.1

I've tested installing to Linux Ch.8 GOG from scratch, and it no longer has the pink text issue.

Technically I haven't re-tested the following configurations, hopefully they don't have the issue.
 - French MacOS Ch.8 GOG
 - French MacOS Ch.8 Steam/Mangagamer
 - French Linux Ch.8 Steam/Mangagamer (I haven't retested installing from scratch, but manually applying the new sharedassets seemed to work)

@PeanutButler Since save files between the French and English version of our mod might not be compatible, I would recommend just finishing the English version you're already playing, don't try switching to the French version or your saves might be invalid.
